# Use Node.js LTS version as base image
FROM node:18 as development

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Ensure Next.js is installed
RUN npx next --version

# Copy the rest of your application code to the working directory
COPY . .

# Expose port 3000 for development server
EXPOSE 3000

# Start development server
CMD ["npm", "run", "dev"]
