export const initialValues = {
  title: "",
  moving_from: "",
  moving_to: "",
  total_distance: 0,
  unit: "",
  category_slug: null,
  bed_room_count: null,
  floor_level: null,
  have_lift: null,
  team_configuration: null,
  have_parking_space: null,
  is_parking_ulez_congestion_charges: null,
  is_included_all_charges: null,
  is_individual: null,
  is_company: null,
  moving_date: "",
  is_moving_date_flexible: null,
  extra_moving_service: "",
  is_moving_everything_at_once: null,
  is_driver_flexible_to_move_item_at_different_time: null,
  have_animal: null,
  description: "",
  any_more_move: "",
  status: "ACTIVE",
};
