import "./globals.css";
import { Poppins } from "next/font/google";
import GlobalProvider from "@/components/hoc/GlobalProvider";
import dynamic from 'next/dynamic';
import Head from "next/head";
import Script from "next/script";

// Dynamically import the PendingStatusModal with no SSR
const PendingStatusModal = dynamic(() => import('@/components/PendingStatusModal'), {
  ssr: false,
});

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "MovMonkey",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
      <body className={poppins.className}>
        <Script
          src={`https://maps.googleapis.com/maps/api/js?key=AIzaSyAdepi4YsrlSYhTp8NeWrCKTRVOF2N6naA&libraries=places`}
          strategy="beforeInteractive"
        />
        <GlobalProvider>
          {children}
          <PendingStatusModal />
        </GlobalProvider>
      </body>
    </html>
  );
}
